<html>
    <head>
        <title><?=$this->escape($title);?></title>
    </head>
    <body>
        <?=$this->caps($shout);?>
        <?=$this->block('partial-block');?>
        <?=$this->block('content');?>
    </body>
</html>
